[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/submit"
  to = "/.netlify/functions/submit"
  status = 200

[[redirects]]
  from = "/api/time"
  to = "/.netlify/functions/time"
  status = 200
